AplicacaoDjango/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse

def home(resquest):
    return HttpResponse('<h1>HOME </h1>')

def my_view(resquest):
        HttpResponse.headers
        #return HttpResponse('<h1>VAi torma no cu<h1>')
        #return HttpResponse(HttpResponse.status_code)
        return HttpResponse(HttpResponse.status_code)

urlpatterns = [
    # Página HOME
    path('', home),
    path('admin/', admin.site.urls),
    path('sobre/', my_view),
]

receitas/urls.py
from django.contrib import admin
from django.urls import path
from django.http import HttpResponse
#from receitas.views import home

from . import views

from receitas.views import home, receitas, search
from django.conf.urls.static import static
from django.conf import settings


"""
def my_view(resquest):
        HttpResponse.headers
        #return HttpResponse('<h1>VAi torma no cu<h1>')
        #return HttpResponse(HttpResponse.status_code)
        return HttpResponse(HttpResponse.status_code)
"""

# isso afeta a url da aplicação ficando receitas:receita ou receitas:home
app_name = 'receitas'

urlpatterns = [
    # Página HOME
    path('', home, name="home"),
    path('receitas/search/', search, name="search"),
    path('receitas/<int:id>/', receitas, name="receita"),
    path('receitas/category/<int:category_id>/', views.category, name="category"),
       
    
]


# para que se possa acessar um conteúdo diretamente com por exemplo um imagem
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

receitas/models.py
from django.db import models
# Elemento User presente na base de dados
from django.contrib.auth.models import User
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.name
    

# os atributos vão virar colunas
class Receitas(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    slug = models.SlugField(unique=True)
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    
    # auto_now_add chamado na criação na depois
    created_at = models.DateTimeField(auto_now_add=True)
    
    # chamado em alterações
    updated_at = models.DateTimeField(auto_now=True) 
    
    is_published =  models.BooleanField(default=False)
    
    # blank para permitir que não seja obrigatório a importação de uma imagem
    cover = models.ImageField(upload_to='receitas/covers/%Y/%m/%d/', blank=True, default='')
    
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True, default=None)
    
    author = models.ForeignKey(
        # tratamento para quando for deletado ou se pode ficar em branco
        User, on_delete=models.SET_NULL, null=True, blank=True, default=None
    )
    
    
    def __str__(self):
        return self.title

receitas/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404
from receitas.utils.receitas.factory import make_receitas
from receitas.models import Receitas
from django.http import HttpResponse,HttpRequest
from django.http import Http404
from django.db.models import Q
from .utils.receitas.pagination import make_pagination
from django.contrib import messages


#receitas por página
receitas_pagina = 2


# recebe uma view devolve uma responce 
def home(request):
    
    # Objeto herdado em Receitas
    #receitas = Receitas.objects.all().order_by('-id')
    
    # filtra somente pela publicadas
    receitas = Receitas.objects.filter(
        is_published=True
    ).order_by('-id')
    
    page_obj, pagination_range = make_pagination(request, receitas, receitas_pagina)
    
    
    
    
    
    
    #return HttpResponse('<h1>HOME </h1>')
    return render(request, 'receitas/pages/home.html', context={
        #'receitasGerada': [make_receitas() for _ in range(6)],
        'receitasGerada': page_obj,
        'pagination_range' : pagination_range,
    })


def category(request, category_id):
    # Objeto herdado em Receitas
    # Usar category__id dentro de filter para acessar o id de category dentro de models
    #receitas = Receitas.objects.filter(
    #    category__id=category_id,
    #    is_published=True
    #).order_by('-id')  # id decrescente
    
    
    #if not receitas:
        #return HttpResponse(content='Not Found', status='404')
        # ou um ou outro
    #    raise Http404('Not found')
    
    
    
    
    # Passar o model e os filtros
    receitas = get_list_or_404(
        #passando a queryset
        Receitas.objects.filter(
        category__id=category_id,
        is_published=True
        ).order_by('-id')
    )
    
    # Obtendo o primeiro objeto do queryset
    #primeira_receita = receitas.first()
    primeira_receita = receitas[0]
    categoria_nome = primeira_receita.category.name if primeira_receita else 'Categoria Desconhecida'
    
    page_obj, pagination_range = make_pagination(request, receitas, receitas_pagina)
    
    return render(request, 'receitas/pages/category.html', context={
        # Variáveis de contexto que podem ser chamadas dentro do HTML
        'receitasGerada': page_obj,
        'pagination_range': pagination_range,
        
        # f de tipo String
        'title': f'{categoria_nome} - Category | '
    })

    
    
    

# viewer de quando clica na receita
def receitas(request, id):
    #return HttpResponse('<h1>HOME </h1>')
    
    # usando objects para informar páginas não encontradas
    receitaDetalhes = Receitas.objects.filter(
        pk=id,
        is_published=True,
    ).order_by('-id').first()
    
    return render(request, 'receitas/pages/receitas-detail.html', context={
        'receitaGerada': receitaDetalhes,
        'is_detail_page': True,
    })
    
    
def search(request):
    
    # se não receber q o padrã oé None, exitando pesquisa somente com espaço
    #search_term = request.GET.get('q', None)
    # remove espaços laterais
    search_term = request.GET.get('q', '').strip()
    
    if not search_term:
        raise Http404()
    
    
    #__contains para buscar nomes parecidos. (__icontains) maiusculas e minusculas 
    receitasPesquisa = Receitas.objects.filter(
        
        # | = or 
        # __
        Q(
            Q(title__icontains=search_term) |
            Q(description__icontains=search_term),    
        ),
        is_published=True
    
    ).order_by('-id')
    
    page_obj, pagination_range = make_pagination(request, receitas, receitas_pagina)
    
    # o return retorna variaveis para serem usadas nos templates
    return render(request, 'receitas/pages/search.html',{
        'page_title': f'Search for "{search_term}" |',
        'search_term': search_term,
        'receitasGerada': page_obj,
        'pagination_range': pagination_range,
        'additional_url_query' : f'&q={search_term}',
    })

receitas/templates/receitas/pages/category.html
{% extends "global/base.html" %}

{% block title %} {{title}} {% endblock title %}

{% block content %}
<div class="main-content main-content-list container">
   
    <!--receitasGerada esta vindo do views.py do app-->
    {% for receitaGerada in receitasGerada%}
        <!--a veriável receitaGerada vai esta disponível dentro de receitasCards.html-->
        {% include 'receitas/partials/receitasCards.html' %}
    {% endfor %}
    
</div>
{% endblock content %}

receitas/templates/receitas/pages/home.html
{% extends "global/base.html" %}

{% block title %} HOME | {% endblock title %}

{% block content %}

{% if  message%}
<div class="main-content center container">
    
    {% for message in messages %}
        {{ message }}
    {% endfor %}

</div>
{% endif %}

<div class="main-content main-content-list container">
   
    <!--receitasGerada esta vindo do views.py do app-->
    {% for receitaGerada in receitasGerada%}
        <!--a veriável receitaGerada vai esta disponível dentro de receitasCards.html-->
        {% include 'receitas/partials/receitasCards.html' %}
    {% empty%}
        <div class="center">
            <h1>Receitas não encontradas</h1>
        <div>
    {% endfor %}
    
</div>
{% endblock content %}

receitas/templates/receitas/pages/receitas-detail.html
{% extends "global/base.html" %}



{% block title %} {{Receitas.title}} {% endblock title %}

{% block content %}
    <div class="main-content main-content-detail container">
        {% include 'receitas/partials/receitasCards.html' %}
    </div>
{% endblock content %}

receitas/templates/receitas/pages/search.html
{% extends "global/base.html" %}

{% block title %}{{ page_title }}{% endblock title %}

{% block content %}

<!--
<div class="center">
    <h2>O usuário pesquisou por {{search_term}}</h2>
</div>
-->


<div class="main-content main-content-list container">
   
    <!--receitasGerada esta vindo do views.py do app-->
    {% for receitaGerada in receitasGerada%}
        <!--a veriável receitaGerada vai esta disponível dentro de receitasCards.html-->
        {% include 'receitas/partials/receitasCards.html' %}
    {% empty%}
        <div class="center">
            <h1>Receitas não encontradas</h1>
        <div>
    {% endfor %}
    
</div>
{% endblock content %}

receitas/templates/receitas/partials/footer.html
<footer class="main-footer">
    <div class="developer">
        <a href="https://github.com/ANTONIELSONSILVA" target="_blank" rel="noreferrer noopener">By Antonielson Silva</a>
    </div>

    <div class="powered">
        <a href="https://www.djangoproject.com/" target="_blank" rel="noreferrer noopener">Powered by Django</a>
    </div>
</footer>

receitas/templates/receitas/partials/head.html
{% load static %}

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/brands.min.js" integrity="sha512-ojD9xRtdGdJLd9K/vMhV6GyO8G9wVrofDXmX4AjrKPctyKTLaVVwuAJhZanincPnSprZv1Nc3iDpxIi/6+Xv7A==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="stylesheet" src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/js/solid.min.js" integrity="sha512-BR7kmAOY+DL7VrNcDauAY0nOqLp58prNOuwMmes8bd5ET13AAorhPqzbCtH8BsGGG0/TTs9W4Tokbj4tMhFUFw==" crossorigin="anonymous" referrerpolicy="no-referrer">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@100..900&display=swap" rel="stylesheet">
    <!--
    <script src='https://kit.fontawesome.com/a076d05399.js' crossorigin='anonymous'></script>
    -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    
    <link rel="stylesheet" href="{% static 'receitas/css/style.css' %}">



receitas/templates/receitas/partials/header.html
<header class="main-header-container">
    <div class="main-header">
        <h1>
            <a class="main-logo" href="{% url 'receitas:home' %}">
                <i class="fa fa-address-book main-logo-icon"></i>
                <span class="main-logo-text">Receitas</span>
            </a>
        </h1>
    </div>
</header>

receitas/templates/receitas/partials/pagination.html
{% if receitasGerada.has_other_pages %}

    <div class="container pagination">
        
        <div class="pagination-conten">

            {% if pagination_range.first_page_out_of_range %}
                <a class="page-link page-item" href="?page=1{{ additional_url_query }}">1</a>
                <span class="page-item">...</span>
            {% endif %}

            {% for page in pagination_range.pagination %}
                {% if  pagination_range.current_page == page %}               
                    <a class="page-link page-item page-current" href="?page={{page}}{{ additional_url_query }}">{{ page  }}</a>
                {% else  %}
                    <a class="page-link page-item" href="?page={{page}}{{ additional_url_query }}">{{ page  }}</a>
                {% endif %}
            {% endfor %}

            {% if pagination_range.last_page_out_of_range %}
                <span class="page-item">...</span>
                <a class="page-link page-item" href="?page={{pagination_range.total_pages}}{{ additional_url_query }}">{{pagination_range.total_pages}}</a>
            {% endif %}

        </div>
    
    </div>

{% endif %}

receitas/templates/receitas/partials/receitasCards.html
{% load static %}

<div class="receita receita-list-item">


    <!--if para evitar erro e mostra imagem somente quando ela foi cadastrada-->
    {% if receitaGerada.cover %}
        <div class="receita-cover">

            <a href="{% url 'receitas:receita' receitaGerada.id%}">
                <!--<img src="{% static 'receitas/receitas-cover.png' %}" alt="receitas-cover"/>-->
                <img src="{{ receitaGerada.cover.url }}" alt="receitas-cover"/>
            </a>

        </div>
    {% endif %}




    <div class="receita-title-container">
        <a href="{% url 'receitas:receita' receitaGerada.id%}">
            <h2 class="receita-title">{{receitaGerada.title}}</h2>
        </a>

    </div>

    <div class="receita-author">
            <span class="receita-author-item">
                <i class="fa fa-user"></i>

                {% if  receitaGerada.author is not None%}

                    <!--mostra do nome do autor se houver-->
                    {% if receitaGerada.author.fisrt_name %}
                        {{receitaGerada.author.fisrt_name}} {{receitaGerada.author.last_name}}
                    {% else %}
                        {{receitaGerada.author.username}}
                    {% endif %}

                {% else %}
                    Desconhecido
                {% endif %}
                
            </span>
        

        
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>

            <!--Verificar na documentação o formato data e hora-->

            {{ receitaGerada.created_at|date:"d/m/Y" }} às {{ receitaGerada.created_at|date:"H:i" }}

        </span>
        

        <!-- onde gera a receita-->
        {% if receitaGerada.category is not None %}
        <span class="receita-author-item">
            <!--<a href="/receitas/category/cafe-da-manha/">-->
                <a href="{% url 'receitas:category' receitaGerada.category.id %}">
                    <i class="fas fa-layer-group"></i>
                    <span>{{ receitaGerada.category.name }}</span>
                </a>                           
        </span>
        {% endif %}

    </div>


    {% if is_detail_page is not True %}
        <div class="receita-content">
            <p>{{ receitaGerada.description }}</p>
        </div>
    {% else  %}
        <div class="preparation-steps">
            <p>{{ receitaGerada.preparation_steps| linebreaks }}</p>
        </div>
    {% endif %}




    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fa fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                {{ receitaGerada.preparation_time }} {{ receitaGerada.preparation_time_unit }} 
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fa fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                {{ receitaGerada.servings }} {{ receitaGerada.servings_unit }}
            </div>
        </div>

    </div>

    {% if is_detail_page is not True %}
    <footer class="receita-footer">
        <a class="receita-read-more button button-dark button-full-width" href="{% url 'receitas:receita' receitaGerada.id%}">
            <i class="fa fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>
    {% endif %}

    

</div>


receitas/templates/receitas/partials/receitasCards6.html
{% load static %}

<div class="receita receita-list-item">
    <div class="receita-cover">
        <img src="{% static 'receitas/receitas-cover.png' %}" alt="receitas-cover"/>
    </div>
    <div class="receita-title-container">
        <h2 class="receita-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="receita-author">
        <span class="receita-author-item">
            <i class="fa fa-user"></i>
            Antonielson Silva
        </span>
        
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2024 às 11:21
        </span>
        
        <span class="receita-author-item">
            <a href="/receitas/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
                                   
        </span>

    </div>

    <div class="receita-content">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, harum.</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fa fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                0 Minutos
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fa fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                0 Porções
            </div>
        </div>

    </div>

    <footer class="receita-footer">
        <a class="receita-read-more button button-dark button-full-width" href="/recipes/3/">
            <i class="fa fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>

</div>

<div class="receita receita-list-item">
    <div class="receita-cover">
        <img src="{% static 'receitas/receitas-cover.png' %}" alt="receitas-cover"/>
    </div>
    <div class="receita-title-container">
        <h2 class="receita-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="receita-author">
        <span class="receita-author-item">
            <i class="fa fa-user"></i>
            Antonielson Silva
        </span>
        
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2024 às 11:21
        </span>
        
        <span class="receita-author-item">
            <a href="/receitas/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
                                   
        </span>

    </div>

    <div class="receita-content">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, harum.</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fa fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                0 Minutos
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fa fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                0 Porções
            </div>
        </div>

    </div>

    <footer class="receita-footer">
        <a class="receita-read-more button button-dark button-full-width" href="/recipes/3/">
            <i class="fa fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>

</div>
<div class="receita receita-list-item">
    <div class="receita-cover">
        <img src="{% static 'receitas/receitas-cover.png' %}" alt="receitas-cover"/>
    </div>
    <div class="receita-title-container">
        <h2 class="receita-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="receita-author">
        <span class="receita-author-item">
            <i class="fa fa-user"></i>
            Antonielson Silva
        </span>
        
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2024 às 11:21
        </span>
        
        <span class="receita-author-item">
            <a href="/receitas/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
                                   
        </span>

    </div>

    <div class="receita-content">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, harum.</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fa fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                0 Minutos
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fa fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                0 Porções
            </div>
        </div>

    </div>

    <footer class="receita-footer">
        <a class="receita-read-more button button-dark button-full-width" href="/recipes/3/">
            <i class="fa fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>

</div>
<div class="receita receita-list-item">
    <div class="receita-cover">
        <img src="{% static 'receitas/receitas-cover.png' %}" alt="receitas-cover"/>
    </div>
    <div class="receita-title-container">
        <h2 class="receita-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="receita-author">
        <span class="receita-author-item">
            <i class="fa fa-user"></i>
            Antonielson Silva
        </span>
        
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2024 às 11:21
        </span>
        
        <span class="receita-author-item">
            <a href="/receitas/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
                                   
        </span>

    </div>

    <div class="receita-content">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, harum.</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fa fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                0 Minutos
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fa fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                0 Porções
            </div>
        </div>

    </div>

    <footer class="receita-footer">
        <a class="receita-read-more button button-dark button-full-width" href="/recipes/3/">
            <i class="fa fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>

</div>
<div class="receita receita-list-item">
    <div class="receita-cover">
        <img src="{% static 'receitas/receitas-cover.png' %}" alt="receitas-cover"/>
    </div>
    <div class="receita-title-container">
        <h2 class="receita-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="receita-author">
        <span class="receita-author-item">
            <i class="fa fa-user"></i>
            Antonielson Silva
        </span>
        
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2024 às 11:21
        </span>
        
        <span class="receita-author-item">
            <a href="/receitas/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
                                   
        </span>

    </div>

    <div class="receita-content">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, harum.</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fa fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                0 Minutos
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fa fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                0 Porções
            </div>
        </div>

    </div>

    <footer class="receita-footer">
        <a class="receita-read-more button button-dark button-full-width" href="/recipes/3/">
            <i class="fa fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>

</div>
<div class="receita receita-list-item">
    <div class="receita-cover">
        <img src="{% static 'receitas/receitas-cover.png' %}" alt="receitas-cover"/>
    </div>
    <div class="receita-title-container">
        <h2 class="receita-title">Lorem ipsum dolor sit amet.</h2>
    </div>

    <div class="receita-author">
        <span class="receita-author-item">
            <i class="fa fa-user"></i>
            Antonielson Silva
        </span>
        
        <span class="receita-author-item">
            <i class="fas fa-calendar-alt"></i>
            16/10/2024 às 11:21
        </span>
        
        <span class="receita-author-item">
            <a href="/receitas/category/cafe-da-manha/">
                <i class="fas fa-layer-group"></i>
                <span>Café da manhã</span>
            </a>
                                   
        </span>

    </div>

    <div class="receita-content">
        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum, harum.</p>
    </div>

    <div class="receita-meta-container">
        <div class="receita-meta receita-preparation">
            <h3 class="receita-meta-title"><i class="fa fa-stopwatch"></i> Preparo</h3>
            <div class="receita-meta-text">
                0 Minutos
            </div>
        </div>
        <div class="receita-meta receita-servings">
            <h3 class="receita-meta-title"><i class="fa fa-pizza-slice"></i> Porções</h3>
            <div class="receita-meta-text">
                0 Porções
            </div>
        </div>

    </div>

    <footer class="receita-footer">
        <a class="receita-read-more button button-dark button-full-width" href="/recipes/3/">
            <i class="fa fa-eye"></i>
            <span>Ver mais...</span>
        </a>
    </footer>

</div>

receitas/templates/receitas/partials/search.html
<div class="search-container">
    <div>
        <form action="{% url "receitas:search" %}" method="GET" class="search-form">
            <!--required informa input em branco-->
            <input type="search" class="search-input" name="q" value="{{ search_term}}" required>
            <button type="submit" class="search-button"><i class='fa fa-search'></i></button>
        </form>
    </div>
</div>